/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/v8_engine/scene.gltf -o src/components/V8EngineModel.tsx --types 
Author: Tomaso (https://sketchfab.com/Tomasoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/disassembled-v8-engine-block-3026bd87ca3945d6829d24c86ce695f0
Title: Disassembled V8 Engine Block
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_86: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_91: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_104: THREE.Mesh
    Object_105: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_113: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/v8_engine/scene.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.94, -0.797, 2.783]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      </group>
      <group position={[-2.467, 4.757, 0.037]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.325, 4.748, 0.132]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-0.09, -3.316, -1.612]}>
        <mesh geometry={nodes.Object_75.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} />
      </group>
      <group position={[-0.076, 0.503, -4.246]}>
        <mesh geometry={nodes.Object_78.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_79.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.676, 2.169, 1.976]} scale={[0.989, 1, 1]}>
        <mesh geometry={nodes.Object_81.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_82.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_83.geometry} material={materials['Material.011']} />
      </group>
      <group position={[2.495, 2.179, -1.877]} scale={[1.089, 1, 1]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_87.geometry} material={materials['Material.011']} />
      </group>
      <group position={[0, -3.634, 0]}>
        <mesh geometry={nodes.Object_91.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_93.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_95.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_97.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_99.geometry} material={materials['Material.016']} />
      </group>
      <group position={[-2.152, 3.879, 0.001]}>
        <mesh geometry={nodes.Object_108.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_109.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['Material.019']} />
      </group>
      <group position={[-0.086, 5.158, 0]}>
        <mesh geometry={nodes.Object_112.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Object_113.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_114.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Object_115.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_116.geometry} material={materials['Material.022']} />
      </group>
      <group position={[1.999, 3.879, -0.08]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Object_118.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Object_120.geometry} material={materials['Material.019']} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.005']} position={[-2.163, 5.043, 2.177]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.006']} position={[-1.244, 4.421, -2.06]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.010']} position={[-0.958, -2.602, 2.15]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.002']} position={[-0.602, -3.083, 2.23]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.002']} position={[-0.613, -3.069, 1.904]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.010']} position={[1.103, -2.439, 2.211]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.002']} position={[0.758, -2.831, 2.028]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.002']} position={[0.47, -3.089, 2.346]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.010']} position={[-1.294, -2.385, -1.873]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.002']} position={[-0.699, -3.065, -1.814]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.010']} position={[1.282, -2.307, -1.824]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.002']} position={[0.745, -2.854, -2]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.010']} position={[-1.443, -2.262, -0.537]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.002']} position={[-0.951, -2.495, -0.481]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.002']} position={[-0.943, -2.494, -0.793]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.002']} position={[0.733, -2.541, -0.715]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.010']} position={[1.304, -2.242, -0.515]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.010']} position={[-1.295, -2.333, 0.777]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.002']} position={[-0.951, -2.495, 0.832]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['Material.010']} position={[0.926, -2.442, 0.811]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.002']} position={[0.644, -2.587, 0.602]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.002']} position={[0.64, -2.595, 0.29]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['Material.005']} position={[2, 5.043, -2.012]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials['Material.006']} position={[1.057, 4.503, 2.256]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['Material.014']} position={[-1.373, -8.6, 2.24]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['Material.001']} position={[-2.426, 7.377, 1.917]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.001']} position={[2.174, 7.152, 0.012]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Material.001']} position={[0, 0, -5.345]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Material.003']} position={[-0.087, -0.625, 4.144]} />
      <mesh geometry={nodes.Object_71.geometry} material={materials['Material.009']} position={[3.986, 0.931, 0.382]} />
      <mesh geometry={nodes.Object_73.geometry} material={materials['Material.009']} position={[-4.086, 0.94, 0.322]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials['Material.008']} position={[-0.09, -5.062, -1.22]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials['Material.018']} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Material.018']} />
      <mesh geometry={nodes.Object_103.geometry} material={materials['Material.018']} />
      <mesh geometry={nodes.Object_104.geometry} material={materials['Material.018']} />
      <mesh geometry={nodes.Object_105.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_122.geometry} material={materials['Material.002']} position={[0, 0, -0.021]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials['Material.001']} position={[0, -4.719, 3]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['Material.002']} position={[0.18, -3.931, 2.008]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials['Material.002']} position={[-0.373, -3.89, -1.804]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['Material.002']} position={[-0.055, -2.549, 0.849]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials['Material.002']} position={[-0.242, -2.595, 0.612]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials['Material.002']} position={[1.974, -0.282, 2.78]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials['Material.001']} position={[1.974, 5.076, 2.283]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials['Material.002']} position={[-1.629, -1.161, 2.304]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials['Material.002']} position={[-1.629, -1.161, -1.019]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials['Material.002']} position={[-1.635, -6.29, -1.929]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials['Material.002']} position={[-1.629, -1.244, -1.904]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials['Material.002']} position={[1.447, -1.244, -1.91]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['Material.002']} position={[1.428, -1.161, -1.031]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials['Material.002']} position={[1.428, -1.161, 2.307]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials['Material.002']} position={[-1.707, 7.089, 1.368]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials['Material.002']} position={[1.558, 7.084, -1.135]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials['Material.002']} position={[3.998, 0.922, -2.409]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials['Material.002']} position={[-4.103, 0.936, 2.573]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials['Material.001']} position={[-2.125, 5.082, 2.604]} />
    </group>
  )
}

useGLTF.preload('/v8_engine/scene.gltf')
